version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - .:/app
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/Dockerfile-php
    image: php:7-fpm-alpine
    volumes:
      - .:/app
    working_dir: /app
  db:
    container_name: db
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_STORAGE_DIR}:/app"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
